#TIENDA
USE Tienda;
SELECT nombre FROM `producto`;
SELECT nombre, precio FROM `producto`;
SELECT * FROM `producto`;
SELECT nombre, concat(precio,"€"), concat(precio,"$") FROM `producto`;
SELECT nombre as 'nombre de producto', concat(precio,"€") as 'euros', concat(precio,"$") as 'dolares' FROM `producto` WHERE 1;
SELECT UPPER(nombre),precio FROM `producto` WHERE 1;
SELECT LOWER(nombre),precio FROM `producto` WHERE 1;
SELECT nombre,UPPER(SUBSTRING(nombre, 1, 2)) FROM `producto` WHERE 1;
SELECT nombre, ROUND(precio) FROM `producto` WHERE 1;
SELECT nombre, TRUNCATE(precio,0) FROM `producto` WHERE 1;
SELECT codigo_fabricante FROM `producto` WHERE 1;
SELECT DISTINCT codigo_fabricante FROM `producto` WHERE 1;
SELECT nombre FROM `fabricante` WHERE 1 ORDER BY nombre ASC;
SELECT nombre FROM `fabricante` WHERE 1 ORDER BY nombre DESC;
SELECT nombre FROM `producto` WHERE 1 ORDER BY nombre ASC, precio DESC;
SELECT * FROM `fabricante` WHERE 1 LIMIT 1,5;
SELECT * FROM `fabricante` WHERE 1 LIMIT 4,2;
SELECT nombre, precio FROM `producto` WHERE 1 ORDER BY Precio ASC LIMIT 1,1;
SELECT nombre, precio FROM `producto` WHERE 1 ORDER BY Precio DESC LIMIT 1,1;
SELECT nombre FROM `producto` WHERE codigo_fabricante = 2;
SELECT producto.nombre, producto.precio, fabricante.nombre  FROM `producto` INNER JOIN fabricante WHERE 1;
SELECT producto.nombre, producto.precio, fabricante.nombre  FROM `producto` INNER JOIN fabricante WHERE 1 ORDER BY fabricante.nombre ASC;
SELECT producto.codigo, producto.nombre, fabricante.codigo, fabricante.nombre  FROM `producto` INNER JOIN fabricante WHERE 1;
SELECT producto.nombre, producto.precio, fabricante.nombre  FROM `producto` INNER JOIN fabricante WHERE 1 ORDER BY producto.precio ASC LIMIT 1,1;
SELECT producto.nombre, producto.precio, fabricante.nombre  FROM `producto` INNER JOIN fabricante WHERE 1 ORDER BY producto.precio DESC LIMIT 1,1;
SELECT producto.*  FROM `producto` INNER JOIN fabricante WHERE fabricante.nombre='Lenovo';
SELECT producto.*  FROM `producto` INNER JOIN fabricante WHERE fabricante.nombre='Crucial' AND producto.precio>200;
SELECT producto.*  FROM `producto` INNER JOIN fabricante WHERE fabricante.nombre='Asus' OR fabricante.nombre='Hewlett-Packard' OR fabricante.nombre='Seagate';
SELECT producto.*  FROM `producto` INNER JOIN fabricante WHERE fabricante.nombre IN ('Asus','Hewlett-Packard','Seagate');
SELECT producto.nombre, producto.precio FROM `producto` INNER JOIN fabricante WHERE fabricante.nombre LIKE '%e';
SELECT producto.nombre, producto.precio, fabricante.nombre FROM `producto` INNER JOIN fabricante WHERE fabricante.nombre LIKE '%w%';
SELECT producto.nombre, producto.precio, fabricante.nombre FROM `producto` INNER JOIN fabricante WHERE producto.precio>=180 ORDER BY producto.precio DESC, producto.nombre ASC;
SELECT fabricante.codigo, fabricante.nombre FROM fabricante WHERE EXISTS (SELECT producto.codigo_fabricante FROM producto WHERE producto.codigo_fabricante = fabricante.codigo);
SELECT fabricante.nombre, producto.nombre FROM `fabricante` LEFT JOIN producto ON producto.codigo_fabricante = fabricante.codigo;
SELECT fabricante.nombre FROM fabricante WHERE NOT EXISTS (SELECT NULL FROM producto WHERE producto.codigo_fabricante = fabricante.codigo);                    
SELECT producto.* FROM producto WHERE exists (SELECT fabricante.codigo FROM fabricante WHERE producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = 'LENOVO');
SELECT * FROM producto WHERE producto.precio  = (SELECT MAX(producto.precio) FROM producto WHERE producto.codigo_fabricante = (SELECT fabricante.codigo FROM fabricante WHERE fabricante.nombre = 'Lenovo'));
SELECT nombre FROM producto WHERE producto.precio  = (SELECT MAX(producto.precio) FROM producto WHERE producto.codigo_fabricante = (SELECT fabricante.codigo FROM fabricante WHERE fabricante.nombre = 'Lenovo'));
SELECT nombre FROM producto WHERE producto.precio  = (SELECT MIN(producto.precio) FROM producto WHERE producto.codigo_fabricante = (SELECT fabricante.codigo FROM fabricante WHERE fabricante.nombre = 'Hewlett-Packard'));
SELECT nombre, precio FROM producto WHERE producto.precio  >= (SELECT MAX(producto.precio) FROM producto WHERE producto.codigo_fabricante = (SELECT fabricante.codigo FROM fabricante WHERE fabricante.nombre = 'Lenovo'));
SELECT nombre, precio FROM producto WHERE precio > (SELECT AVG(producto.precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus'));
#UNIVERSIDAD
USE Universidad;
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo='alumno' ORDER BY apellido1 ASC, apellido2 ASC, nombre ASC;
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo='alumno' AND telefono IS NULL;
SELECT apellido1, apellido2, nombre FROM persona WHERE YEAR(fecha_nacimiento) ='1999';
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo='profesor' AND telefono IS NULL AND nif LIKE'%k';
SELECT nombre FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7; 
SELECT persona.apellido1, persona.apellido2, persona.nombre, departamento.nombre FROM persona INNER JOIN departamento ORDER BY persona.apellido1 ASC, persona.apellido2 ASC, persona.nombre ASC; 
SELECT asignatura.nombre, curso_escolar.anyo_inicio, curso_escolar.anyo_fin FROM persona INNER JOIN alumno_se_matricula_asignatura ON alumno_se_matricula_asignatura.id_alumno = persona.id INNER JOIN asignatura ON asignatura.id =  alumno_se_matricula_asignatura.id_asignatura INNER JOIN curso_escolar ON curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar WHERE persona.nif='26902806M';
SELECT DISTINCT departamento.nombre FROM departamento INNER JOIN profesor ON profesor.id_departamento = departamento.id INNER JOIN asignatura ON asignatura.id_profesor = profesor.id_profesor INNER JOIN grado ON grado.id = asignatura.id_grado WHERE grado.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT DISTINCT persona.nombre FROM persona INNER JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE curso_escolar.anyo_inicio = '2018' AND curso_escolar.anyo_fin = '2019';
#UNIVERSIDAD clàusules LEFT JOIN i RIGHT JOIN.
SELECT departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM persona LEFT JOIN profesor ON profesor.id_profesor = persona.id LEFT JOIN departamento ON departamento.id = profesor.id_departamento WHERE 1 ORDER BY departamento.nombre ASC, persona.apellido1 ASC, persona.apellido2 ASC, persona.nombre ASC;
SELECT persona.apellido1, persona.apellido2, persona.nombre FROM persona LEFT JOIN profesor ON profesor.id_profesor = persona.id LEFT JOIN departamento ON departamento.id = profesor.id_departamento WHERE departamento.id IS NULL ORDER BY persona.apellido1 ASC, persona.apellido2 ASC, persona.nombre ASC;
SELECT departamento.nombre FROM departamento LEFT JOIN profesor ON profesor.id_departamento = departamento.id WHERE profesor.id_departamento IS NULL ORDER BY departamento.nombre ASC;
SELECT persona.apellido1, persona.apellido2, persona.nombre FROM persona LEFT JOIN profesor ON profesor.id_profesor = persona.id LEFT JOIN asignatura ON asignatura.id_profesor = profesor.id_profesor WHERE asignatura.id_profesor IS NULL ORDER BY persona.apellido1 ASC, persona.apellido2 ASC, persona.nombre ASC;
SELECT asignatura.nombre FROM asignatura LEFT JOIN profesor ON profesor.id_profesor = asignatura.id_profesor WHERE asignatura.id_profesor IS NULL ORDER BY asignatura.nombre ASC;
SELECT departamento.nombre FROM departamento LEFT JOIN profesor ON profesor.id_departamento = departamento.id LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor LEFT JOIN curso_escolar ON asignatura.curso = curso_escolar.id WHERE asignatura.curso = curso_escolar.id IS NULL ORDER BY departamento.nombre ASC;
#Consultes resum
SELECT COUNT(*) FROM persona WHERE tipo = 'profesor';
SELECT COUNT(*) FROM persona WHERE tipo = 'alumno' AND EXTRACT(YEAR FROM fecha_nacimiento) = '1999';
SELECT COUNT(profesor.id_profesor), departamento.nombre FROM profesor LEFT JOIN departamento ON departamento.id = profesor.id_departamento GROUP BY departamento.nombre ORDER BY COUNT(profesor.id_profesor) DESC;
SELECT COUNT(profesor.id_profesor), departamento.nombre FROM profesor RIGHT JOIN departamento ON departamento.id = profesor.id_departamento GROUP BY departamento.nombre ORDER BY COUNT(profesor.id_profesor) DESC;
SELECT COUNT(asignatura.id), grado.nombre FROM asignatura RIGHT JOIN grado ON asignatura.id_grado = grado.id GROUP BY grado.nombre ORDER BY COUNT(asignatura.id) DESC;
SELECT COUNT(asignatura.id), grado.nombre FROM asignatura RIGHT JOIN grado ON asignatura.id_grado = grado.id GROUP BY grado.nombre HAVING COUNT(asignatura.id) >40 ORDER BY COUNT(asignatura.id) DESC;
SELECT grado.nombre, asignatura.tipo, COUNT(asignatura.creditos) FROM grado RIGHT JOIN asignatura ON asignatura.id_grado = grado.id GROUP BY grado.nombre ORDER BY COUNT(asignatura.creditos) DESC;
SELECT curso_escolar.anyo_inicio, COUNT(alumno_se_matricula_asignatura.id_alumno) FROM alumno_se_matricula_asignatura RIGHT JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id GROUP BY curso_escolar.anyo_inicio;
SELECT persona.id, persona.apellido1, persona.apellido2, persona.nombre, COUNT(asignatura.id_profesor) FROM persona LEFT JOIN asignatura ON persona.id = asignatura.id_profesor GROUP BY persona.id ORDER BY COUNT(asignatura.id_profesor) DESC;
SELECT * from persona WHERE fecha_nacimiento  = (SELECT min(fecha_nacimiento) FROM persona WHERE tipo = 'alumno');
SELECT persona.nombre, departamento.nombre, asignatura.nombre FROM persona INNER JOIN profesor ON persona.id = profesor.id_profesor INNER JOIN departamento ON profesor.id_departamento = departamento.id LEFT JOIN asignatura ON asignatura.id_profesor = profesor.id_profesor WHERE asignatura.id_profesor = profesor.id_profesor IS NULL;